"""Model card generation.

The brief requires "a documented model or system card". This renders one from
the registry manifest and the latest evaluation, so the card cannot drift away
from the model it describes: it is regenerated by ``phishguard card`` and by CI
rather than maintained by hand.

Structure follows the Model Cards convention (Mitchell et al.) with the
sections a security deployment additionally needs: the threat model, the
defensive controls, and the residual-risk register.
"""

from __future__ import annotations

from typing import Any

from phishguard.adversarial.taxonomy import OUT_OF_SCOPE, describe_taxonomy
from phishguard.data.loaders import describe_datasets
from phishguard.defenses.controls import describe_defenses
from phishguard.models.detector import PhishGuardDetector


def _fmt(value: Any, digits: int = 4) -> str:
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    if value is None:
        return "-"
    return str(value)


def _table(rows: list[dict[str, Any]], columns: list[tuple[str, str]]) -> str:
    if not rows:
        return "_Not available in this run._\n"
    head = "| " + " | ".join(t for _, t in columns) + " |"
    sep = "|" + "|".join("---" for _ in columns) + "|"
    body = ["| " + " | ".join(_fmt(r.get(k, "")) for k, _ in columns) + " |" for r in rows]
    return "\n".join([head, sep, *body]) + "\n"


def render_model_card(
    detector: PhishGuardDetector,
    manifest: dict[str, Any],
    evaluation: dict[str, Any] | None = None,
) -> str:
    """Produce the model card as Markdown."""
    evaluation = evaluation or {}
    clean = evaluation.get("clean", {})
    rob = evaluation.get("robustness", {})
    described = detector.describe()
    training = described.get("training") or {}

    out: list[str] = []
    a = out.append

    a("# Model card - PhishGuard\n")
    a(
        "**Adversarially Robust Phishing Defense using Email, URL and "
        "Behavioral Features** (capstone BAI-17)\n"
    )

    a("## Model details\n")
    a(f"- **Version**: `{described['model_version']}`")
    a(f"- **Trained**: {described.get('trained_at') or 'unknown'}")
    a(
        f"- **Type**: calibrated logistic fusion over "
        f"{len(described['members'])} heterogeneous members"
    )
    a(f"- **Members**: {', '.join(described['members'])}")
    a(f"- **Feature families**: {', '.join(described['feature_families'])}")
    a(f"- **Engineered features**: {training.get('feature_contract', {}).get('n_features', 'n/a')}")
    a(f"- **Calibration**: {described['calibration_method']}")
    a(f"- **Active defences**: {', '.join(described['active_defense_ids'])}")
    env = manifest.get("environment", {})
    if env:
        a(
            f"- **Built with**: Python {env.get('python')}, "
            f"scikit-learn {env.get('scikit_learn')}, numpy {env.get('numpy')}"
        )
    a("")

    a("## Intended use\n")
    a(
        "Assessing inbound email at a mail gateway or in a SOC triage queue, "
        "producing a calibrated phishing probability, a three-way decision band "
        "and an evidence list an analyst can act on.\n"
    )
    a(
        "**In scope**: organisational inbound email where header, URL and "
        "sender-relationship context are available.\n"
    )
    a("**Out of scope**, and not safe to use for:\n")
    a(
        "- Deciding to block mail with no human review path. The REVIEW band "
        "exists because the model is not the last word."
    )
    a("- Attributing an attack to a person or organisation.")
    a(
        "- Any use where a missed detection carries irreversible harm without a "
        "compensating control."
    )
    a(
        "- Languages and mail cultures absent from the training corpus; "
        "performance there is unmeasured, not merely lower.\n"
    )

    a("## Training data\n")
    prov = manifest.get("provenance", {})
    a(f"- **Corpus**: {prov.get('corpus', 'synthetic')}")
    a(
        f"- **Split strategy**: {prov.get('split_strategy', 'grouped')} "
        "(campaign-disjoint, near-duplicate scrubbed)"
    )
    a(
        f"- **Training messages**: {training.get('n_fit', 'n/a')} for members, "
        f"{training.get('n_stack', 'n/a')} for fusion, "
        f"{training.get('n_cal', 'n/a')} for calibration"
    )
    a(
        f"- **Adversarial augmentation**: "
        f"+{training.get('n_adversarial_augmented', 0)} perturbed phishing examples"
    )
    a(f"- **Leakage audit**: {'passed' if prov.get('leakage_passed', True) else 'FAILED'}\n")
    a("### Corpora referenced\n")
    a(
        _table(
            describe_datasets(),
            [
                ("name", "Dataset"),
                ("kind", "Format"),
                ("licence", "Licence"),
                ("notes", "Notes"),
            ],
        )
    )

    a("## Performance\n")
    if clean:
        a(
            _table(
                [
                    {"metric": "Macro F1", "value": clean.get("macro_f1")},
                    {"metric": "PR-AUC", "value": clean.get("pr_auc")},
                    {"metric": "ROC-AUC", "value": clean.get("roc_auc")},
                    {"metric": "Recall (phishing)", "value": clean.get("recall_phish")},
                    {"metric": "False-positive rate", "value": clean.get("false_positive_rate")},
                ],
                [("metric", "Metric"), ("value", "Value")],
            )
        )
    else:
        a("_Run `phishguard evaluate` to populate this section._\n")

    if evaluation.get("baselines"):
        a("### Compared with baselines\n")
        rows = [
            {
                "system": "B0 analyst checklist (no learning)",
                **evaluation["baselines"]["B0_rule_checklist"],
            },
            {
                "system": "B1 TF-IDF + logistic regression",
                **evaluation["baselines"]["B1_tfidf_logreg"],
            },
            {"system": "PhishGuard fusion", **clean},
        ]
        a(
            _table(
                rows,
                [
                    ("system", "System"),
                    ("macro_f1", "Macro F1"),
                    ("pr_auc", "PR-AUC"),
                    ("false_positive_rate", "FPR"),
                ],
            )
        )

    if evaluation.get("banded_decision"):
        b = evaluation["banded_decision"]
        a("### Operating point\n")
        a(
            f"Thresholds: REVIEW at {described['thresholds']['review']}, "
            f"BLOCK at {described['thresholds']['block']}.\n"
        )
        a(
            f"- {b['allow']} allowed / {b['review']} to review / {b['block']} blocked "
            f"({b['review_rate']:.1%} of traffic reaches a human)"
        )
        a(
            f"- Phishing auto-allowed: **{b['missed_phish']}**; "
            f"legitimate auto-blocked: **{b['blocked_ham']}**\n"
        )

    a("## Threat model\n")
    a(
        "The adversary is a competent phishing operator with full control of the "
        "message they send and black-box access to the verdict, under a query "
        "budget. They cannot fabricate the recipient's correspondence history, "
        "age their own domain retroactively, or send from the brand's genuine "
        "domain.\n"
    )
    a(
        _table(
            describe_taxonomy(),
            [
                ("id", "ID"),
                ("name", "Attack family"),
                ("capability", "Attacker capability"),
                ("attacker_cost", "Cost"),
            ],
        )
    )
    a("### Explicitly out of scope\n")
    a(
        _table(
            [dict(o) for o in OUT_OF_SCOPE],
            [
                ("id", "ID"),
                ("threat", "Threat"),
                ("why", "Why out of scope"),
                ("mitigation_elsewhere", "Handled by"),
            ],
        )
    )

    a("## Defensive controls\n")
    a(
        _table(
            describe_defenses(),
            [
                ("id", "ID"),
                ("name", "Control"),
                ("cost", "Cost"),
                ("residual", "Residual gap"),
            ],
        )
    )

    if rob:
        a("## Measured robustness\n")
        a(
            f"- Attack budget {rob.get('budget')} queries against "
            f"{rob.get('attacked_messages')} phishing messages"
        )
        a(
            f"- **Attack success rate: {_fmt(rob.get('attack_success_rate'), 3)}** "
            "(raw-score surface, an upper bound on real attacker success)"
        )
        a(
            f"- Macro F1 under attack: {_fmt(rob.get('adversarial_macro_f1'))} "
            f"(clean {_fmt(rob.get('clean_macro_f1'))}, "
            f"drop {_fmt(rob.get('macro_f1_drop'))})\n"
        )
        if rob.get("residual_risk_register"):
            a("### Residual-risk register\n")
            a(
                _table(
                    rob["residual_risk_register"],
                    [
                        ("family_id", "ID"),
                        ("family", "Attack family"),
                        ("measured_attack_success_rate", "ASR"),
                        ("likelihood", "Likelihood"),
                        ("impact", "Impact"),
                        ("residual_risk", "Residual"),
                        ("compensating_control", "Compensating control"),
                    ],
                )
            )

    a("## Ethical considerations and privacy\n")
    a(
        "- **Data minimisation.** No message content is stored. The audit trail "
        "holds a salted digest of the subject, a pseudonymised sender identifier, "
        "the sender's domain, sizes, the verdict and the evidence titles."
    )
    a(
        "- **No content in logs.** Structured logs carry request ids, scores and "
        "domains; the logging layer drops any field that could hold content."
    )
    a(
        "- **No outbound fetching.** URLs are never resolved and attachments are "
        "never opened, so the system cannot leak victim telemetry to an attacker "
        "or be turned into an SSRF primitive."
    )
    a(
        "- **Human oversight is structural.** The REVIEW band routes uncertain "
        "messages to an analyst; feedback is recorded but never retrains the "
        "model automatically."
    )
    a(
        "- **Asymmetric harms.** A false positive delays legitimate business "
        "communication; a false negative may cost credentials or money. The "
        "operating point is chosen on a false-positive budget for that reason, "
        "and both numbers are reported rather than averaged away."
    )
    a(
        "- **Named-entity risk.** The brand and domain lists are heuristics. A "
        "legitimate organisation whose domain resembles a brand's can be "
        "penalised; the REVIEW band and the analyst feedback loop exist to catch "
        "that, and the lists are reviewable in "
        "`src/phishguard/features/lexicons.py`.\n"
    )

    a("## Limitations\n")
    a(
        "1. The corpus is synthetic. It is campaign-structured, difficulty-"
        "balanced and leakage-audited, but it is a model of phishing rather than "
        "a sample of it; comparative results transfer more reliably than absolute "
        "ones."
    )
    from phishguard.adversarial.transforms import TRANSFORMS

    n_families = len({t.family for t in TRANSFORMS})
    a(
        f"2. Robustness is measured against this suite of {len(TRANSFORMS)} transforms in "
        f"{n_families} families. A genuinely novel attack family is by definition untested."
    )
    a(
        "3. Behavioural features assume a mail gateway. Without them the system "
        "degrades to email and URL evidence and records that it did."
    )
    a(
        "4. Calibration is measured in-distribution. Under drift the "
        "probabilities move, which is why `/api/v1/stats` tracks the score "
        "distribution over time."
    )
    a(
        "5. The system detects; it does not remediate. Quarantine, user "
        "notification and takedown are downstream responsibilities.\n"
    )

    a("## Maintenance\n")
    a(
        "- **Retrain** when the analyst-disagreement rate reported by "
        "`/api/v1/stats` rises materially, or when the score distribution shifts."
    )
    a(
        "- **Re-run the adversarial suite** on every model change; the acceptance "
        "gates block a release whose robustness regressed."
    )
    a(
        "- **Review the brand and TLD lists** quarterly; they are the fastest-"
        "ageing part of the system."
    )
    a("- Regenerate this card with `phishguard card` after every training run.\n")
    return "\n".join(out)
